twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        projet_couverture_directory: '%projet_couverture_directory%'
        projet_couverture_local: '%projet_couverture_local%'
